version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://tunemeld:${POSTGRES_PASSWORD}@postgres:5432/tunemeld
      - REDIS_URL=redis://redis:6379/1
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONPATH=/app/backend:/app
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=tunemeld
      - POSTGRES_USER=tunemeld
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
