[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.etl"

[deploy]
startCommand = "python django_backend/etl_cron.py"
restartPolicyType = "NEVER"
cronSchedule = "0 3 * * 6"  # Every Saturday at 3 AM UTC

[healthcheck]
type = "NONE"  # Cron jobs don't need health checks
