# Generated by Django 4.2.24 on 2025-10-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_play_count_models"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="playlistmodel",
            index=models.Index(
                fields=["genre", "service", "position"],
                name="playlists_genre_i_41d81a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawplaylistdatamodel",
            index=models.Index(
                fields=["genre", "service", "-id"],
                name="raw_playlis_genre_i_a9748c_idx",
            ),
        ),
    ]
