# Generated by Django 4.2.24 on 2025-10-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_play_count_models"),
    ]

    operations = [
        # This migration was already applied manually
        # Mark as complete without any operations
    ]
