# Generated by Django 4.2.25 on 2025-10-10 00:03

from django.db import migrations, models


def add_genius_fields_if_not_exist(apps, schema_editor):
    """Add genius fields only if they don't already exist."""
    with schema_editor.connection.cursor() as cursor:
        # Check if genius_url column exists
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='tracks' AND column_name='genius_url'
            """
        )
        if not cursor.fetchone():
            cursor.execute(
                """
                ALTER TABLE tracks
                ADD COLUMN genius_url VARCHAR(200) NULL
                """
            )

        # Check if genius_lyrics column exists
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='tracks' AND column_name='genius_lyrics'
            """
        )
        if not cursor.fetchone():
            cursor.execute(
                """
                ALTER TABLE tracks
                ADD COLUMN genius_lyrics TEXT NULL
                """
            )


def reverse_genius_fields(apps, schema_editor):
    """Remove genius fields."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE tracks DROP COLUMN IF EXISTS genius_url")
        cursor.execute("ALTER TABLE tracks DROP COLUMN IF EXISTS genius_lyrics")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_critical_indexes"),
    ]

    operations = [
        migrations.RunPython(add_genius_fields_if_not_exist, reverse_genius_fields),
    ]
