# Generated by Django 4.2.25 on 2025-10-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_critical_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackmodel",
            name="genius_lyrics",
            field=models.TextField(
                blank=True, help_text="Full song lyrics from Genius", null=True
            ),
        ),
        migrations.AddField(
            model_name="trackmodel",
            name="genius_url",
            field=models.URLField(
                blank=True, help_text="Genius lyrics page URL", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="playlistmodel",
            index=models.Index(
                fields=["genre", "service", "position"],
                name="playlists_genre_i_41d81a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawplaylistdatamodel",
            index=models.Index(
                fields=["genre", "service", "-id"],
                name="raw_playlis_genre_i_a9748c_idx",
            ),
        ),
    ]
