# Generated by Django 4.2.24 on 2025-10-11 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_genius_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackFeatureModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isrc",
                    models.CharField(
                        db_index=True,
                        help_text="International Standard Recording Code (12 characters)",
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$", "Invalid ISRC format"
                            )
                        ],
                    ),
                ),
                (
                    "danceability",
                    models.FloatField(help_text="Spotify danceability (0-1)"),
                ),
                ("energy", models.FloatField(help_text="Spotify energy (0-1)")),
                ("valence", models.FloatField(help_text="Spotify valence (0-1)")),
                (
                    "acousticness",
                    models.FloatField(help_text="Spotify acousticness (0-1)"),
                ),
                (
                    "instrumentalness",
                    models.FloatField(help_text="Spotify instrumentalness (0-1)"),
                ),
                (
                    "speechiness",
                    models.FloatField(help_text="Spotify speechiness (0-1)"),
                ),
                ("liveness", models.FloatField(help_text="Spotify liveness (0-1)")),
                ("tempo", models.FloatField(help_text="Spotify tempo (BPM)")),
                ("loudness", models.FloatField(help_text="Spotify loudness (dB)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "track_features",
            },
        ),
        migrations.AddConstraint(
            model_name="trackfeaturemodel",
            constraint=models.UniqueConstraint(
                fields=("isrc",), name="unique_track_feature_isrc"
            ),
        ),
    ]
