# Generated by Django 4.2.24 on 2025-10-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_trackfeaturemodel_trackmodel_genius_lyrics_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS playlists_genre_i_41d81a_idx
                ON core_playlistmodel (genre_id, service_id, position);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS playlists_genre_i_41d81a_idx;
            """,
        ),
    ]
