# Generated by Django 4.2.25 on 2025-10-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_fix_duplicate_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawplaylistdatamodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="rawplaylistdatamodel",
            index=models.Index(
                fields=["updated_at"], name="raw_playlis_updated_763d0f_idx"
            ),
        ),
    ]
