# Generated by Django 4.2.24 on 2025-09-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_service_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("sort_field", models.CharField(max_length=50)),
                (
                    "sort_order",
                    models.CharField(
                        choices=[("asc", "Ascending"), ("desc", "Descending")],
                        default="asc",
                        max_length=4,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order_index", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ranks",
                "ordering": ["order_index"],
                "indexes": [
                    models.Index(
                        fields=["order_index"], name="ranks_order_i_005754_idx"
                    ),
                    models.Index(fields=["is_active"], name="ranks_is_acti_c3b5b5_idx"),
                ],
            },
        ),
    ]
