# Generated by Django 4.2.24 on 2025-09-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rank",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveIndex(
            model_name="rank",
            name="ranks_order_i_005754_idx",
        ),
        migrations.RemoveIndex(
            model_name="rank",
            name="ranks_is_acti_c3b5b5_idx",
        ),
        migrations.RemoveField(
            model_name="rank",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="rank",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="rank",
            name="order_index",
        ),
        migrations.RemoveField(
            model_name="rank",
            name="updated_at",
        ),
    ]
