# Generated by Django 4.2.24 on 2025-09-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_rank_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
