# Generated by Django 4.2.24 on 2025-09-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_is_default_to_rank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rank",
            name="is_default",
        ),
    ]
