# Generated by Django 4.2.24 on 2025-09-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_is_default_from_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="data_field",
            field=models.CharField(
                default="rank",
                help_text="Exact field name in track data (e.g., 'rank', 'spotifyCurrentViewCount')",
                max_length=50,
            ),
        ),
    ]
