# Generated by Django 4.2.24 on 2025-09-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rank_data_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="icon_url",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="rank",
            name="icon_url",
            field=models.CharField(default="", max_length=200),
        ),
    ]
