# Generated by Django 4.2.24 on 2025-09-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rank_data_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="icon_class",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Font Awesome icon class (e.g., 'fab fa-spotify')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="rank",
            name="icon_class",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Font Awesome icon class (e.g., 'fab fa-spotify', 'fab fa-youtube')",
                max_length=50,
            ),
        ),
    ]
