# Generated by Django 4.2.24 on 2025-09-20 13:11

from django.db import migrations


def add_icon_classes(apps, schema_editor):
    """Add Font Awesome icon classes to existing genres and ranks."""
    Genre = apps.get_model('core', 'Genre')
    Rank = apps.get_model('core', 'Rank')

    # Update genres with icons
    genre_icons = {
        'dance': 'fas fa-music',
        'rap': 'fas fa-microphone-alt',
        'country': 'fas fa-guitar',
        'pop': 'fas fa-compact-disc',
    }

    for genre_name, icon_class in genre_icons.items():
        Genre.objects.filter(name=genre_name).update(icon_class=icon_class)

    # Update ranks with icons
    rank_icons = {
        'rank': 'fas fa-list-ol',
        'spotify_view_count': 'fab fa-spotify',
        'youtube_view_count': 'fab fa-youtube',
    }

    for rank_name, icon_class in rank_icons.items():
        Rank.objects.filter(name=rank_name).update(icon_class=icon_class)


def reverse_icon_classes(apps, schema_editor):
    """Remove icon classes."""
    Genre = apps.get_model('core', 'Genre')
    Rank = apps.get_model('core', 'Rank')

    Genre.objects.all().update(icon_class='')
    Rank.objects.all().update(icon_class='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_genre_icon_class_rank_icon_class'),
    ]

    operations = [
        migrations.RunPython(add_icon_classes, reverse_icon_classes),
    ]
