# Generated by Django 4.2.24 on 2025-09-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_populate_icon_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="icon_url",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="rank",
            name="icon_url",
            field=models.CharField(max_length=200),
        ),
    ]
