# Generated by Django 4.2.24 on 2025-09-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_make_icon_url_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltrackviewcount",
            name="weekly_change_percentage",
            field=models.FloatField(
                blank=True, help_text="Percentage change from one week ago", null=True
            ),
        ),
    ]
