# Generated by Django 4.2.24 on 2025-09-23 21:25

from django.db import migrations


def create_total_service(apps, schema_editor):
    Service = apps.get_model('core', 'Service')
    Service.objects.get_or_create(
        name='total',
        defaults={
            'display_name': 'Total Views',
            'icon_url': '/images/tunemeld.png',
        }
    )


def reverse_create_total_service(apps, schema_editor):
    Service = apps.get_model('core', 'Service')
    Service.objects.filter(name='total').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_weekly_change_and_total_service"),
    ]

    operations = [
        migrations.RunPython(create_total_service, reverse_create_total_service),
    ]
