# Generated by Django 4.2.24 on 2025-09-23 21:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_create_total_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregateViewCount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "isrc",
                    models.CharField(
                        db_index=True,
                        help_text="International Standard Recording Code (12 characters)",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$", "Invalid ISRC format"
                            )
                        ],
                    ),
                ),
                (
                    "aggregate_key",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier for the type of aggregation (e.g., 'total', 'youtube_spotify', 'streaming_only')",
                        max_length=50,
                    ),
                ),
                (
                    "current_view_count",
                    models.BigIntegerField(
                        help_text="Total aggregated view count across all services in this aggregate"
                    ),
                ),
                (
                    "services_included",
                    models.CharField(
                        help_text="Comma-separated list of services included (e.g., 'youtube,spotify,apple_music')",
                        max_length=200,
                    ),
                ),
                (
                    "youtube_count",
                    models.BigIntegerField(
                        blank=True,
                        help_text="YouTube views in this aggregate",
                        null=True,
                    ),
                ),
                (
                    "spotify_count",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Spotify views in this aggregate",
                        null=True,
                    ),
                ),
                (
                    "apple_music_count",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Apple Music views in this aggregate",
                        null=True,
                    ),
                ),
                (
                    "soundcloud_count",
                    models.BigIntegerField(
                        blank=True,
                        help_text="SoundCloud views in this aggregate",
                        null=True,
                    ),
                ),
                (
                    "daily_change",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Absolute change from previous day",
                        null=True,
                    ),
                ),
                (
                    "daily_change_percentage",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage change from previous day",
                        null=True,
                    ),
                ),
                (
                    "weekly_change",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Absolute change from one week ago",
                        null=True,
                    ),
                ),
                (
                    "weekly_change_percentage",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage change from one week ago",
                        null=True,
                    ),
                ),
                (
                    "monthly_change",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Absolute change from one month ago",
                        null=True,
                    ),
                ),
                (
                    "monthly_change_percentage",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage change from one month ago",
                        null=True,
                    ),
                ),
                (
                    "recorded_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date this aggregate was calculated",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "aggregate_view_counts",
                "indexes": [
                    models.Index(
                        fields=["isrc", "aggregate_key", "recorded_date"],
                        name="aggregate_v_isrc_b9320d_idx",
                    ),
                    models.Index(
                        fields=["aggregate_key", "recorded_date"],
                        name="aggregate_v_aggrega_d7506b_idx",
                    ),
                    models.Index(
                        fields=["recorded_date"], name="aggregate_v_recorde_893250_idx"
                    ),
                ],
                "unique_together": {("isrc", "aggregate_key", "recorded_date")},
            },
        ),
    ]
