# Generated by Django 4.2.24 on 2025-09-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_add_aggregate_view_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rank",
            name="icon_url",
        ),
    ]
