# Generated by Django 4.2.24 on 2025-09-23 22:00

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_rank_icon_url"),
    ]

    operations = [
        # Drop the existing AggregateViewCount table
        migrations.DeleteModel(
            name="AggregateViewCount",
        ),

        # Create the new AggregateViewCount table with service-based structure
        migrations.CreateModel(
            name="AggregateViewCount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "isrc",
                    models.CharField(
                        db_index=True,
                        help_text="International Standard Recording Code (12 characters)",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$", "Invalid ISRC format"
                            )
                        ],
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.service",
                        help_text="Service for this play count record (individual service or 'all' for aggregated)"
                    ),
                ),
                (
                    "current_play_count",
                    models.BigIntegerField(
                        help_text="Current play count for this service (or total for 'all' service)"
                    ),
                ),
                (
                    "weekly_change",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Absolute change from one week ago",
                        null=True,
                    ),
                ),
                (
                    "weekly_change_percentage",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage change from one week ago",
                        null=True,
                    ),
                ),
                (
                    "recorded_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date this aggregate was calculated",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "aggregate_view_counts",
                "indexes": [
                    models.Index(
                        fields=["service", "isrc", "recorded_date"],
                        name="aggregate_v_service_isrc_date_idx",
                    ),
                    models.Index(
                        fields=["recorded_date"],
                        name="aggregate_v_recorded_date_idx"
                    ),
                    models.Index(
                        fields=["isrc", "recorded_date"],
                        name="aggregate_v_isrc_date_idx"
                    ),
                ],
                "unique_together": {("service", "isrc", "recorded_date")},
            },
        ),
    ]
