# Generated by Django 4.2.24 on 2025-09-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_restructure_aggregate_view_count"),
    ]

    operations = [
        # Rename table for HistoricalTrackViewCount to HistoricalTrackPlayCount
        migrations.RunSQL(
            "ALTER TABLE historical_track_view_counts RENAME TO historical_track_play_counts;",
            reverse_sql="ALTER TABLE historical_track_play_counts RENAME TO historical_track_view_counts;"
        ),

        # Rename columns in historical_track_play_counts
        migrations.RunSQL(
            "ALTER TABLE historical_track_play_counts RENAME COLUMN current_view_count TO current_play_count;",
            reverse_sql="ALTER TABLE historical_track_play_counts RENAME COLUMN current_play_count TO current_view_count;"
        ),
        migrations.RunSQL(
            "ALTER TABLE historical_track_play_counts RENAME COLUMN daily_view_change TO daily_play_change;",
            reverse_sql="ALTER TABLE historical_track_play_counts RENAME COLUMN daily_play_change TO daily_view_change;"
        ),

        # Rename table for AggregateViewCount to AggregatePlayCount
        migrations.RunSQL(
            "ALTER TABLE aggregate_view_counts RENAME TO aggregate_play_counts;",
            reverse_sql="ALTER TABLE aggregate_play_counts RENAME TO aggregate_view_counts;"
        ),
    ]
