# Generated by Django 4.2.24 on 2025-09-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_clean_slate_lookup_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='icon_class',
            field=models.CharField(default='', max_length=50, help_text='CSS class for genre icon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rank',
            name='icon_class',
            field=models.CharField(default='', max_length=50, help_text='CSS class for rank icon'),
            preserve_default=False,
        ),
    ]
