# Generated by Django 4.2.24 on 2025-09-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_remove_etl_run_id_from_genre_service"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="rank",
            name="ranks_etl_run_443516_idx",
        ),
        migrations.AlterUniqueTogether(
            name="rank",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="rank",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_rank_name"
            ),
        ),
        migrations.RemoveField(
            model_name="rank",
            name="etl_run_id",
        ),
    ]
