# Generated by Django 4.2.24 on 2025-09-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_etl_run_id_from_rank"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="track",
            name="tracks_etl_run_5e76c3_idx",
        ),
        migrations.AlterUniqueTogether(
            name="track",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("isrc",), name="unique_track_isrc"
            ),
        ),
        migrations.RemoveField(
            model_name="track",
            name="etl_run_id",
        ),
    ]
