# Generated by Django 4.2.24 on 2025-09-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_remove_etl_run_id_from_tracks"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="playlist",
            name="playlists_etl_run_a70eb6_idx",
        ),
        migrations.RemoveIndex(
            model_name="rawplaylistdata",
            name="raw_playlis_etl_run_e3dc5a_idx",
        ),
        migrations.RemoveIndex(
            model_name="servicetrack",
            name="service_tra_etl_run_2f6d81_idx",
        ),
        migrations.AlterUniqueTogether(
            name="playlist",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="rawplaylistdata",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="servicetrack",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="playlist",
            constraint=models.UniqueConstraint(
                fields=("service", "genre", "position"), name="unique_playlist_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="rawplaylistdata",
            constraint=models.UniqueConstraint(
                fields=("service", "genre"), name="unique_raw_playlist_service_genre"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetrack",
            constraint=models.UniqueConstraint(
                fields=("service", "genre", "position"),
                name="unique_service_track_position",
            ),
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="etl_run_id",
        ),
        migrations.RemoveField(
            model_name="rawplaylistdata",
            name="etl_run_id",
        ),
        migrations.RemoveField(
            model_name="servicetrack",
            name="etl_run_id",
        ),
    ]
