# Generated by Django 4.2.23 on 2025-09-12 18:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Internal genre identifier (lowercase, underscores only)",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z_]+$",
                                "Genre names must be lowercase with underscores",
                            )
                        ],
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable genre name", max_length=100
                    ),
                ),
            ],
            options={
                "db_table": "genres",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Internal service identifier",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z][A-Za-z0-9_]*$",
                                "Service names must be alphanumeric",
                            )
                        ],
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable service name", max_length=100
                    ),
                ),
                (
                    "icon_url",
                    models.CharField(
                        default="",
                        help_text="URL to service icon image",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "db_table": "services",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isrc",
                    models.CharField(
                        help_text="International Standard Recording Code (12 characters)",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$", "Invalid ISRC format"
                            )
                        ],
                    ),
                ),
                (
                    "track_name",
                    models.CharField(help_text="Name of the track", max_length=500),
                ),
                (
                    "artist_name",
                    models.CharField(help_text="Primary artist name", max_length=500),
                ),
                (
                    "album_name",
                    models.CharField(
                        blank=True, help_text="Album name", max_length=500, null=True
                    ),
                ),
                (
                    "spotify_url",
                    models.URLField(
                        blank=True, help_text="Spotify track URL", null=True
                    ),
                ),
                (
                    "apple_music_url",
                    models.URLField(
                        blank=True, help_text="Apple Music track URL", null=True
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True, help_text="YouTube track URL", null=True
                    ),
                ),
                (
                    "soundcloud_url",
                    models.URLField(
                        blank=True, help_text="SoundCloud track URL", null=True
                    ),
                ),
                (
                    "album_cover_url",
                    models.URLField(
                        blank=True, help_text="Album cover image URL", null=True
                    ),
                ),
                (
                    "aggregate_rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Cross-service aggregate ranking",
                        null=True,
                    ),
                ),
                (
                    "aggregate_score",
                    models.FloatField(
                        blank=True, help_text="Cross-service aggregate score", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "etl_run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="ETL run identifier for blue-green deployments",
                    ),
                ),
            ],
            options={
                "db_table": "tracks",
                "indexes": [
                    models.Index(
                        fields=["track_name", "artist_name"],
                        name="tracks_track_n_cecb83_idx",
                    ),
                    models.Index(
                        fields=["artist_name"], name="tracks_artist__0a8ef7_idx"
                    ),
                    models.Index(
                        fields=["etl_run_id"], name="tracks_etl_run_5e76c3_idx"
                    ),
                    models.Index(fields=["isrc"], name="tracks_isrc_426685_idx"),
                ],
                "unique_together": {("isrc", "etl_run_id")},
            },
        ),
        migrations.CreateModel(
            name="ServiceTrack",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "position",
                    models.PositiveIntegerField(help_text="Position in playlist"),
                ),
                (
                    "track_name",
                    models.CharField(help_text="Name of the track", max_length=500),
                ),
                (
                    "artist_name",
                    models.CharField(help_text="Primary artist name", max_length=500),
                ),
                (
                    "album_name",
                    models.CharField(
                        blank=True, help_text="Album name", max_length=500, null=True
                    ),
                ),
                (
                    "service_url",
                    models.URLField(help_text="Service-specific track URL"),
                ),
                (
                    "isrc",
                    models.CharField(
                        help_text="International Standard Recording Code (12 characters)",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$", "Invalid ISRC format"
                            )
                        ],
                    ),
                ),
                (
                    "album_cover_url",
                    models.URLField(
                        blank=True, help_text="Album cover image URL", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "etl_run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="ETL run identifier for blue-green deployments",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.genre"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.service"
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to consolidated Track record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_tracks",
                        to="core.track",
                    ),
                ),
            ],
            options={
                "db_table": "service_tracks",
            },
        ),
        migrations.CreateModel(
            name="RawPlaylistData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("playlist_url", models.URLField(help_text="Original playlist URL")),
                (
                    "playlist_name",
                    models.CharField(
                        blank=True, help_text="Playlist display name", max_length=255
                    ),
                ),
                (
                    "playlist_cover_url",
                    models.URLField(blank=True, help_text="Playlist cover image URL"),
                ),
                (
                    "playlist_cover_description_text",
                    models.TextField(blank=True, help_text="Cover image description"),
                ),
                ("data", models.JSONField(help_text="Raw JSON data from service API")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "etl_run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="ETL run identifier for blue-green deployments",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        help_text="Genre of this playlist data",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.genre",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Service this data came from",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.service",
                    ),
                ),
            ],
            options={
                "db_table": "raw_playlist_data",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField()),
                (
                    "isrc",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="International Standard Recording Code (12 characters)",
                        max_length=12,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$", "Invalid ISRC format"
                            )
                        ],
                    ),
                ),
                (
                    "etl_run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="ETL run identifier for blue-green deployments",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.genre"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.service"
                    ),
                ),
                (
                    "service_track",
                    models.ForeignKey(
                        help_text="Reference to the normalized service track record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to="core.servicetrack",
                    ),
                ),
            ],
            options={
                "db_table": "playlists",
                "ordering": ["service", "genre", "position"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalViewCount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "isrc",
                    models.CharField(
                        db_index=True,
                        help_text="International Standard Recording Code (12 characters)",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$", "Invalid ISRC format"
                            )
                        ],
                    ),
                ),
                (
                    "view_count",
                    models.BigIntegerField(
                        help_text="View count at this point in time"
                    ),
                ),
                (
                    "delta_count",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Change in view count from previous day",
                        null=True,
                    ),
                ),
                (
                    "recorded_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date this count was recorded",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.service"
                    ),
                ),
            ],
            options={
                "db_table": "historical_view_counts",
            },
        ),
        migrations.CreateModel(
            name="ViewCount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "isrc",
                    models.CharField(
                        db_index=True,
                        help_text="International Standard Recording Code (12 characters)",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$", "Invalid ISRC format"
                            )
                        ],
                    ),
                ),
                (
                    "view_count",
                    models.BigIntegerField(help_text="Current view/play count"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(help_text="When this count was last fetched"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.service"
                    ),
                ),
            ],
            options={
                "db_table": "view_counts",
                "indexes": [
                    models.Index(
                        fields=["service"], name="view_counts_service_3e4aa6_idx"
                    ),
                    models.Index(
                        fields=["last_updated"], name="view_counts_last_up_0540eb_idx"
                    ),
                    models.Index(
                        fields=["view_count"], name="view_counts_view_co_2e64d3_idx"
                    ),
                ],
                "unique_together": {("isrc", "service")},
            },
        ),
        migrations.AddIndex(
            model_name="servicetrack",
            index=models.Index(
                fields=["service", "genre"], name="service_tra_service_96adaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicetrack",
            index=models.Index(fields=["isrc"], name="service_tra_isrc_256b90_idx"),
        ),
        migrations.AddIndex(
            model_name="servicetrack",
            index=models.Index(
                fields=["track_name", "artist_name"],
                name="service_tra_track_n_45500e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicetrack",
            index=models.Index(
                fields=["service", "isrc"], name="service_tra_service_64f0ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicetrack",
            index=models.Index(
                fields=["etl_run_id"], name="service_tra_etl_run_2f6d81_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="servicetrack",
            unique_together={("service", "genre", "position", "etl_run_id")},
        ),
        migrations.AddIndex(
            model_name="rawplaylistdata",
            index=models.Index(
                fields=["genre", "service"], name="raw_playlis_genre_i_150b29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawplaylistdata",
            index=models.Index(
                fields=["created_at"], name="raw_playlis_created_114d4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawplaylistdata",
            index=models.Index(
                fields=["playlist_url"], name="raw_playlis_playlis_a02f88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawplaylistdata",
            index=models.Index(
                fields=["etl_run_id"], name="raw_playlis_etl_run_e3dc5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(
                fields=["service", "genre"], name="playlists_service_7e971b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(fields=["isrc"], name="playlists_isrc_f1b2fb_idx"),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(
                fields=["etl_run_id"], name="playlists_etl_run_a70eb6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playlist",
            unique_together={("service", "genre", "position", "etl_run_id")},
        ),
        migrations.AddIndex(
            model_name="historicalviewcount",
            index=models.Index(
                fields=["service", "recorded_date"],
                name="historical__service_b9ee87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historicalviewcount",
            index=models.Index(
                fields=["recorded_date"], name="historical__recorde_686e9a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="historicalviewcount",
            unique_together={("isrc", "service", "recorded_date")},
        ),
    ]
