# Generated by Django 5.2.5 on 2025-08-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
    ]
