# Generated by Django 4.2.23 on 2025-09-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE service_tracks DROP CONSTRAINT IF EXISTS service_tracks_service_id_genre_id_position_d4f90b0e_uniq;
                ALTER TABLE service_tracks DROP CONSTRAINT IF EXISTS service_tracks_service_id_genre_id_position_etl_run_id_510434b1_uniq;
            """,
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE service_tracks ADD CONSTRAINT service_tracks_service_id_genre_id_position_etl_run_id_510434b1_uniq UNIQUE (service_id, genre_id, position, etl_run_id);",
            reverse_sql="ALTER TABLE service_tracks DROP CONSTRAINT IF EXISTS service_tracks_service_id_genre_id_position_etl_run_id_510434b1_uniq;",
        ),
    ]
