# Generated by Django 4.2 on 2025-09-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawplaylistdata",
            name="playlist_cover_url",
            field=models.URLField(
                blank=True, help_text="Playlist cover image URL", null=True
            ),
        ),
    ]
