# Generated by Django 4.2 on 2025-08-17 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="isrc",
            field=models.CharField(blank=True, db_index=True, help_text="International Standard Recording Code (12 characters)", max_length=12, null=True, validators=[django.core.validators.RegexValidator("^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$", "Invalid ISRC format")]),
        ),
    ]
