# Generated by Django 4.2 on 2025-08-14 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_genre_created_at_remove_service_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('service_track_id', models.CharField(blank=True, max_length=200, null=True)),
                ('track_name', models.CharField(max_length=500)),
                ('artist_name', models.CharField(max_length=500)),
                ('album_name', models.CharField(blank=True, max_length=500, null=True)),
                ('isrc', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('spotify_url', models.URLField(blank=True, null=True)),
                ('apple_music_url', models.URLField(blank=True, null=True)),
                ('soundcloud_url', models.URLField(blank=True, null=True)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('album_cover_url', models.URLField(blank=True, null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genre')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
            options={
                'db_table': 'playlist_tracks',
                'ordering': ['service', 'genre', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='playlisttrack',
            index=models.Index(fields=['service', 'genre'], name='playlist_tr_service_bae90a_idx'),
        ),
        migrations.AddIndex(
            model_name='playlisttrack',
            index=models.Index(fields=['isrc'], name='playlist_tr_isrc_293506_idx'),
        ),
        migrations.AddIndex(
            model_name='playlisttrack',
            index=models.Index(fields=['track_name', 'artist_name'], name='playlist_tr_track_n_709d45_idx'),
        ),
    ]
