# Generated by Django 4.2.23 on 2025-09-11 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_drop_old_unique_constraints"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE playlists DROP CONSTRAINT IF EXISTS playlists_service_id_genre_id_position_43bfa2eb_uniq;
                ALTER TABLE playlists DROP CONSTRAINT IF EXISTS playlists_service_id_genre_id_position_etl_run_id_246d44c3_uniq;
            """,
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE playlists ADD CONSTRAINT playlists_service_id_genre_id_position_etl_run_id_246d44c3_uniq UNIQUE (service_id, genre_id, position, etl_run_id);",
            reverse_sql="ALTER TABLE playlists DROP CONSTRAINT IF EXISTS playlists_service_id_genre_id_position_etl_run_id_246d44c3_uniq;",
        ),
    ]
