# Generated by Django 4.2.23 on 2025-09-11 15:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_fix_view_counts_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name='rawplaylistdata',
            name='etl_run_id',
            field=models.UUIDField(default=uuid.uuid4, help_text="ETL run identifier for blue-green deployments"),
        ),
        migrations.AddField(
            model_name='servicetrack',
            name='etl_run_id',
            field=models.UUIDField(default=uuid.uuid4, help_text="ETL run identifier for blue-green deployments"),
        ),
        migrations.AddField(
            model_name='playlist',
            name='etl_run_id',
            field=models.UUIDField(default=uuid.uuid4, help_text="ETL run identifier for blue-green deployments"),
        ),
        migrations.AddField(
            model_name='track',
            name='etl_run_id',
            field=models.UUIDField(default=uuid.uuid4, help_text="ETL run identifier for blue-green deployments"),
        ),
        migrations.AddIndex(
            model_name='rawplaylistdata',
            index=models.Index(fields=['etl_run_id'], name='core_rawplaylistdata_etl_run_id_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetrack',
            index=models.Index(fields=['etl_run_id'], name='core_servicetrack_etl_run_id_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['etl_run_id'], name='core_playlist_etl_run_id_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['etl_run_id'], name='core_track_etl_run_id_idx'),
        ),
    ]
