# Generated by Django 4.2.23 on 2025-09-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_rawplaylistdata_playlist_cover_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawplaylistdata",
            name="playlist_cover_url",
            field=models.URLField(
                blank=True,
                default="https://placeholder.com/cover.m3u8",
                help_text="Playlist cover image URL",
            ),
            preserve_default=False,
        ),
    ]
