# Generated by Django 4.2.23 on 2025-09-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_fix_playlist_unique_constraints"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE service_tracks DROP CONSTRAINT IF EXISTS service_tracks_service_id_genre_id_position_d4f90b0e_uniq;
                ALTER TABLE service_tracks DROP CONSTRAINT IF EXISTS service_tracks_service_id_genre_id_position_etl_run_id_9e8c4b2f_uniq;
            """,
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE service_tracks ADD CONSTRAINT service_tracks_service_id_genre_id_position_etl_run_id_9e8c4b2f_uniq UNIQUE (service_id, genre_id, position, etl_run_id);",
            reverse_sql="ALTER TABLE service_tracks DROP CONSTRAINT IF EXISTS service_tracks_service_id_genre_id_position_etl_run_id_9e8c4b2f_uniq;",
        ),
    ]
