# Generated by Django 4.2.23 on 2025-09-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_rawplaylistdata_playlist_cover_url"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalViewCount",
            new_name="HistoricalTrackViewCount",
        ),
        migrations.RenameModel(
            old_name="ViewCount",
            new_name="TrackViewCount",
        ),
        migrations.RenameIndex(
            model_name="historicaltrackviewcount",
            new_name="historical__service_a20407_idx",
            old_name="historical__service_b9ee87_idx",
        ),
        migrations.RenameIndex(
            model_name="historicaltrackviewcount",
            new_name="historical__recorde_fcfdb3_idx",
            old_name="historical__recorde_686e9a_idx",
        ),
        migrations.RenameIndex(
            model_name="trackviewcount",
            new_name="track_view__service_e192b1_idx",
            old_name="view_counts_service_3e4aa6_idx",
        ),
        migrations.RenameIndex(
            model_name="trackviewcount",
            new_name="track_view__last_up_ae9757_idx",
            old_name="view_counts_last_up_0540eb_idx",
        ),
        migrations.RenameIndex(
            model_name="trackviewcount",
            new_name="track_view__view_co_58e49b_idx",
            old_name="view_counts_view_co_2e64d3_idx",
        ),
        migrations.AlterModelTable(
            name="historicaltrackviewcount",
            table="historical_track_view_counts",
        ),
        migrations.AlterModelTable(
            name="trackviewcount",
            table="track_view_counts",
        ),
    ]
