# Generated by Django 4.2.23 on 2025-09-11 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_fix_service_track_constraints"),
    ]

    operations = [
        # Drop the old primary key constraint and add new auto-incrementing ID
        migrations.RunSQL(
            sql="""
                -- First, add the new ID column as NOT NULL with a sequence
                ALTER TABLE tracks ADD COLUMN id BIGSERIAL;
                -- Drop the old primary key constraint on isrc
                ALTER TABLE tracks DROP CONSTRAINT tracks_pkey;
                -- Make the new id column the primary key
                ALTER TABLE tracks ADD CONSTRAINT tracks_pkey PRIMARY KEY (id);
                -- Add unique constraint on isrc and etl_run_id
                ALTER TABLE tracks DROP CONSTRAINT IF EXISTS tracks_isrc_etl_run_id_key;
                ALTER TABLE tracks ADD CONSTRAINT tracks_isrc_etl_run_id_key UNIQUE (isrc, etl_run_id);
            """,
            reverse_sql="""
                -- Reverse: remove the new constraints and restore old primary key
                ALTER TABLE tracks DROP CONSTRAINT IF EXISTS tracks_isrc_etl_run_id_key;
                ALTER TABLE tracks DROP CONSTRAINT tracks_pkey;
                ALTER TABLE tracks ADD CONSTRAINT tracks_pkey PRIMARY KEY (isrc);
                ALTER TABLE tracks DROP COLUMN id;
            """,
        ),
    ]
