# Generated by Django 4.2.24 on 2025-09-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_historicalviewcount_historicaltrackviewcount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltrackviewcount",
            name="delta_count",
        ),
        migrations.RemoveField(
            model_name="historicaltrackviewcount",
            name="view_count",
        ),
        migrations.AddField(
            model_name="historicaltrackviewcount",
            name="current_view_count",
            field=models.BigIntegerField(default=0, help_text="Current total view count"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaltrackviewcount",
            name="daily_change_percentage",
            field=models.FloatField(blank=True, help_text="Percentage change from previous day", null=True),
        ),
        migrations.AddField(
            model_name="historicaltrackviewcount",
            name="daily_view_change",
            field=models.BigIntegerField(
                blank=True,
                help_text="Absolute change in views from previous day",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="TrackViewCount",
        ),
    ]
