# Generated by Django 4.2.23 on 2025-09-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_fix_service_track_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="track",
            unique_together={("isrc", "etl_run_id")},
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(fields=["isrc"], name="tracks_isrc_426685_idx"),
        ),
    ]
