# Generated by Django 4.2.23 on 2025-09-12 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_fix_service_track_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="track",
            name="isrc",
            field=models.CharField(
                help_text="International Standard Recording Code (12 characters)",
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$", "Invalid ISRC format"
                    )
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="track",
            unique_together={("isrc", "etl_run_id")},
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(fields=["isrc"], name="tracks_isrc_426685_idx"),
        ),
    ]
