# Generated by Django 4.2.24 on 2025-09-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_historicaltrackviewcount_delta_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.CharField(
                default="", help_text="Service description", max_length=500
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rawplaylistdata",
            unique_together={("service", "genre", "etl_run_id")},
        ),
    ]
