# Generated by Django 4.2.23 on 2025-09-12 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_track_id_alter_track_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="track",
            name="isrc",
            field=models.CharField(
                help_text="International Standard Recording Code (12 characters)",
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$", "Invalid ISRC format"
                    )
                ],
            ),
        ),
    ]
