# Generated by Django 4.2.23 on 2025-09-12 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_track_id_alter_track_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="id",
        ),
    ]
