# Generated by Django 4.2.24 on 2025-09-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_service_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="description",
        ),
    ]
