# Generated by Django 4.2.23 on 2025-09-12 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_track_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="id",
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="track",
            name="isrc",
            field=models.CharField(
                help_text="International Standard Recording Code (12 characters)",
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$", "Invalid ISRC format"
                    )
                ],
            ),
        ),
    ]
