# Generated by Django 4.2.23 on 2025-09-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_track_id"),
    ]

    operations = [
        # This migration is a no-op since 0005 already has the correct final state
        # Railway database expects this migration to exist but the changes are already applied
    ]