name: Django Migration & Deployment

on:
  push:
    branches: [ main, master ]
    paths:
      - 'django_backend/core/models.py'
      - 'django_backend/core/migrations/**'
      - 'django_backend/core/management/commands/**'
      - 'Procfile'
      - '.github/workflows/postgres-migration.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'django_backend/core/models.py'
      - 'django_backend/core/migrations/**'
      - 'django_backend/core/management/commands/**'
      - 'Procfile'
  workflow_dispatch:

jobs:
  test-migration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r django_backend/requirements.txt

    - name: Run Django checks
      run: |
        cd django_backend
        python manage.py check
      env:
        SECRET_KEY: test-secret-key-for-ci
        DATABASE_URL: sqlite:///test.db

    - name: Test migrations (dry run)
      run: |
        cd django_backend
        python manage.py makemigrations --dry-run --check
        python manage.py migrate --dry-run
      env:
        SECRET_KEY: test-secret-key-for-ci
        DATABASE_URL: sqlite:///test.db

  deploy-railway:
    runs-on: ubuntu-latest
    needs: test-migration
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js (for Railway CLI)
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Railway CLI
      run: npm install -g @railway/cli@latest

    - name: Deploy to Railway
      run: |
        railway login --token ${{ secrets.RAILWAY_API_TOKEN }}
        railway link --project ${{ secrets.RAILWAY_PROJECT_ID }} --environment production
        railway up --detach
      env:
        RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
