name: update_view_counts

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run-tasks:
    runs-on: ubuntu-latest

    timeout-minutes: 90

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Set PYTHONPATH and Django settings
        run: |
          echo "PYTHONPATH=$PWD:$PWD/django_backend" >> $GITHUB_ENV
          echo "DJANGO_SETTINGS_MODULE=core.settings" >> $GITHUB_ENV

      - name: Run main_view_count.py
        env:
          X_RAPIDAPI_KEY: ${{ secrets.X_RAPIDAPI_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          cd django_backend
          python3 ../playlist_etl/main_view_count.py
